[package]
name = "vimo"
version = "0.1.0"
edition = "2021"
authors = ["Nikhil kashyap <nmknikhilkashyap@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "3.0.0"
